/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CertificateRegistry__factory } from "./CertificateRegistry__factory";
export { DocumentNotary__factory } from "./DocumentNotary__factory";
