import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { Layout } from '../components/layout/Layout';
import { HashDisplay } from '../components/common/Displays';
import { useBackend } from '../context/BackendContext';
import {
  addBatchToBackendChain,
  buildMerkleBatch,
  getBackendChain,
  resetBackendChain,
  tamperBackendBlock,
  validateBackendChain,
  verifyMerkleProof,
} from '../utils/backendApi';
import {
  Activity,
  CheckCircle,
  Database,
  FileStack,
  Loader2,
  Pickaxe,
  RefreshCw,
  Server,
  ShieldCheck,
  Upload,
  XCircle,
  Zap,
} from 'lucide-react';

export function BackendLabPage() {
  const { backendUrl, backendStatus, refreshBackendStatus } = useBackend();
  const [files, setFiles] = useState([]);
  const [batch, setBatch] = useState(null);
  const [chain, setChain] = useState(null);
  const [validation, setValidation] = useState(null);
  const [proofResult, setProofResult] = useState(null);
  const [isWorking, setIsWorking] = useState(false);

  const loadChain = async () => {
    try {
      const result = await getBackendChain();
      setChain(result);
      return result;
    } catch (error) {
      setChain(null);
      return null;
    }
  };

  useEffect(() => {
    loadChain();
  }, []);

  const handleFilesChange = (event) => {
    setFiles(Array.from(event.target.files || []));
    setBatch(null);
    setProofResult(null);
  };

  const handleBuildMerkle = async () => {
    if (!files.length) {
      toast.error('Please choose at least one file');
      return;
    }
    setIsWorking(true);
    try {
      const result = await buildMerkleBatch(files);
      setBatch(result);
      setProofResult(null);
      toast.success('Merkle root and proofs generated by backend');
    } catch (error) {
      toast.error(`Backend error: ${error.message}`);
    } finally {
      setIsWorking(false);
    }
  };

  const handleVerifyFirstProof = async () => {
    if (!batch?.files?.length) return;
    setIsWorking(true);
    try {
      const firstFile = batch.files[0];
      const result = await verifyMerkleProof({
        documentHash: firstFile.documentHash,
        merkleRoot: batch.merkleRoot,
        proof: firstFile.proof,
      });
      setProofResult({ fileName: firstFile.fileName, ...result });
      toast.success(result.valid ? 'Merkle proof is valid' : 'Merkle proof is invalid');
    } catch (error) {
      toast.error(`Verify proof failed: ${error.message}`);
    } finally {
      setIsWorking(false);
    }
  };

  const handleAddBlock = async () => {
    if (!batch) {
      toast.error('Generate a Merkle batch first');
      return;
    }
    setIsWorking(true);
    try {
      const result = await addBatchToBackendChain({
        batchId: batch.batchId,
        merkleRoot: batch.merkleRoot,
        documentCount: batch.fileCount,
        note: 'Document batch registration from CertiChain FE',
      });
      setChain(result.chain);
      toast.success('Batch mined into backend Proof-of-Work chain');
    } catch (error) {
      toast.error(`Add block failed: ${error.message}`);
    } finally {
      setIsWorking(false);
    }
  };

  const handleValidate = async () => {
    setIsWorking(true);
    try {
      const result = await validateBackendChain();
      setValidation(result);
      await loadChain();
      toast[result.valid ? 'success' : 'error'](result.message);
    } catch (error) {
      toast.error(`Validation failed: ${error.message}`);
    } finally {
      setIsWorking(false);
    }
  };

  const handleTamper = async () => {
    setIsWorking(true);
    try {
      const result = await tamperBackendBlock(1);
      setChain(result.chain);
      setValidation({ valid: result.valid, message: result.message });
      toast.error('Block 1 was tampered. Validate chain should fail now.');
    } catch (error) {
      toast.error(`Tamper demo failed: ${error.message}`);
    } finally {
      setIsWorking(false);
    }
  };

  const handleReset = async () => {
    setIsWorking(true);
    try {
      const result = await resetBackendChain();
      setChain(result);
      setBatch(null);
      setProofResult(null);
      setValidation(null);
      toast.success('Backend chain reset');
    } catch (error) {
      toast.error(`Reset failed: ${error.message}`);
    } finally {
      setIsWorking(false);
    }
  };

  return (
    <Layout>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-dark-100">Backend Lab</h1>
        <p className="text-dark-400">Connect the React frontend to the Python/Rust-style dApp backend for hashing, Merkle proof, Proof-of-Work, and chain validation demos.</p>
      </div>

      <div className="glass-card p-6 mb-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${backendStatus.online ? 'bg-emerald-500/20' : 'bg-red-500/20'}`}>
              <Server className={`w-6 h-6 ${backendStatus.online ? 'text-emerald-400' : 'text-red-400'}`} />
            </div>
            <div>
              <p className="font-semibold text-dark-100">Backend API</p>
              <p className="text-sm text-dark-400">{backendUrl}</p>
              <p className={`text-sm ${backendStatus.online ? 'text-emerald-400' : 'text-red-400'}`}>
                {backendStatus.loading ? 'Checking...' : backendStatus.online ? 'Online - FE/BE connected' : 'Offline - start the backend server'}
              </p>
            </div>
          </div>
          <button className="btn-secondary" onClick={refreshBackendStatus} disabled={backendStatus.loading}>
            <RefreshCw className="w-5 h-5" />
            Recheck Backend
          </button>
        </div>
        {!backendStatus.online && (
          <div className="mt-4 p-4 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-200 text-sm">
            Run backend first: <span className="font-mono">python -m uvicorn backend_api.main:app --host 127.0.0.1 --port 8000 --reload</span>
          </div>
        )}
      </div>

      <div className="grid lg:grid-cols-2 gap-6 mb-6">
        <div className="glass-card p-6">
          <div className="flex items-center gap-2 mb-4">
            <FileStack className="w-5 h-5 text-primary-400" />
            <h2 className="font-semibold text-dark-100">1. Upload files to backend</h2>
          </div>
          <p className="text-dark-400 mb-4">The backend calculates SHA-256 file hashes, builds a Merkle Tree, and returns a Merkle Root + proof for each file.</p>
          <label className="block border-2 border-dashed border-dark-600 rounded-xl p-8 text-center cursor-pointer hover:border-primary-500 transition-colors">
            <Upload className="w-10 h-10 mx-auto mb-3 text-dark-400" />
            <span className="text-dark-200">Choose PDF/PNG/JPG/TXT files</span>
            <input type="file" multiple onChange={handleFilesChange} className="hidden" />
          </label>
          {files.length > 0 && (
            <div className="mt-4 text-sm text-dark-400">
              {files.length} file(s) selected: {files.map((file) => file.name).join(', ')}
            </div>
          )}
          <button className="btn-primary mt-4" onClick={handleBuildMerkle} disabled={isWorking || !backendStatus.online}>
            {isWorking ? <Loader2 className="w-5 h-5 animate-spin" /> : <Database className="w-5 h-5" />}
            Generate Merkle Batch
          </button>
        </div>

        <div className="glass-card p-6">
          <div className="flex items-center gap-2 mb-4">
            <ShieldCheck className="w-5 h-5 text-primary-400" />
            <h2 className="font-semibold text-dark-100">2. Merkle proof result</h2>
          </div>
          {!batch ? (
            <p className="text-dark-500">No batch generated yet.</p>
          ) : (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div className="glass-card p-3">
                  <p className="text-dark-500">Batch ID</p>
                  <p className="text-dark-200 font-mono">{batch.batchId}</p>
                </div>
                <div className="glass-card p-3">
                  <p className="text-dark-500">Files</p>
                  <p className="text-dark-200">{batch.fileCount}</p>
                </div>
              </div>
              <HashDisplay label="Merkle Root" hash={batch.merkleRoot} showFull />
              <div className="max-h-52 overflow-y-auto space-y-2">
                {batch.files.map((file) => (
                  <div key={file.fileName} className="p-3 rounded-lg bg-dark-800/50 border border-dark-700">
                    <p className="text-sm text-dark-200">{file.fileName}</p>
                    <p className="text-xs text-dark-500">Proof steps: {file.proof.length}</p>
                    <p className="font-mono text-xs text-primary-400 break-all">{file.documentHash}</p>
                  </div>
                ))}
              </div>
              <div className="flex flex-wrap gap-3">
                <button className="btn-secondary" onClick={handleVerifyFirstProof} disabled={isWorking}>
                  <CheckCircle className="w-5 h-5" />
                  Verify First Proof
                </button>
                <button className="btn-primary" onClick={handleAddBlock} disabled={isWorking}>
                  <Pickaxe className="w-5 h-5" />
                  Mine Batch Block
                </button>
              </div>
              {proofResult && (
                <div className={`p-3 rounded-lg border ${proofResult.valid ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' : 'bg-red-500/10 border-red-500/30 text-red-300'}`}>
                  {proofResult.valid ? 'VALID' : 'INVALID'} proof for {proofResult.fileName}
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      <div className="glass-card p-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
          <div>
            <div className="flex items-center gap-2">
              <Activity className="w-5 h-5 text-primary-400" />
              <h2 className="font-semibold text-dark-100">3. Backend Proof-of-Work Blockchain</h2>
            </div>
            <p className="text-dark-400">The backend mines blocks with nonce and validates previous_hash + PoW. Tamper demo modifies block data to make validation fail.</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button className="btn-secondary" onClick={loadChain} disabled={isWorking}>
              <RefreshCw className="w-5 h-5" /> Load Chain
            </button>
            <button className="btn-secondary" onClick={handleValidate} disabled={isWorking}>
              <Zap className="w-5 h-5" /> Validate
            </button>
            <button className="btn-secondary border-red-500/30 text-red-300" onClick={handleTamper} disabled={isWorking || !chain || chain.length < 2}>
              <XCircle className="w-5 h-5" /> Tamper Block 1
            </button>
            <button className="btn-ghost" onClick={handleReset} disabled={isWorking}>Reset</button>
          </div>
        </div>

        {validation && (
          <div className={`p-4 rounded-lg border mb-4 ${validation.valid ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' : 'bg-red-500/10 border-red-500/30 text-red-300'}`}>
            {validation.valid ? 'VALID CHAIN' : 'INVALID CHAIN'} — {validation.message}
          </div>
        )}

        {!chain ? (
          <p className="text-dark-500">Chain not loaded.</p>
        ) : (
          <div className="space-y-3">
            <div className="flex items-center gap-3 text-sm text-dark-400">
              <span>Difficulty: {chain.difficulty}</span>
              <span>Blocks: {chain.length}</span>
              <span className={chain.valid ? 'text-emerald-400' : 'text-red-400'}>{chain.valid ? 'Valid' : 'Invalid'}</span>
            </div>
            <div className="grid gap-3">
              {chain.blocks.map((block) => (
                <div key={block.index} className="p-4 rounded-xl bg-dark-800/50 border border-dark-700">
                  <div className="flex flex-wrap justify-between gap-3 mb-2">
                    <p className="font-semibold text-dark-100">Block #{block.index}</p>
                    <p className="text-sm text-dark-500">nonce={block.nonce} · {block.miningTime}s</p>
                  </div>
                  <p className="text-xs text-dark-500 mb-2">{block.timestamp}</p>
                  <p className="font-mono text-xs text-primary-400 break-all">hash: {block.hash}</p>
                  <p className="font-mono text-xs text-dark-500 break-all">prev: {block.previousHash}</p>
                  <pre className="mt-3 text-xs text-dark-300 overflow-x-auto bg-dark-950/50 p-3 rounded-lg">{JSON.stringify(block.data, null, 2)}</pre>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}
