import { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useWeb3 } from '../context/Web3Context';
import { useDemo } from '../context/DemoContext';
import { useCertificates } from '../hooks/useCertificates';
import { Layout } from '../components/layout/Layout';
import { FileUpload } from '../components/common/FileUpload';
import { PermissionDenied, LoadingSpinner } from '../components/common/States';
import { AddressDisplay, HashDisplay } from '../components/common/Displays';
import { StatusBadge } from '../components/common/Badges';
import { hashFile, generateMetadataHash, isValidFileType } from '../utils/hash';
import { hashFileWithBackend } from '../utils/backendApi';
import { useBackend } from '../context/BackendContext';
import { generateCertId, formatAddress, isValidAddress } from '../utils/format';
import { CERTIFICATE_TYPES } from '../contracts';
import toast from 'react-hot-toast';
import {
  FileText,
  User,
  Upload,
  Eye,
  Send,
  CheckCircle,
  ExternalLink,
  QrCode,
  Plus,
  Loader2,
} from 'lucide-react';

const INITIAL_FORM = {
  certId: '',
  certName: '',
  certType: 'Course',
  description: '',
  expiryDate: '',
  recipientName: '',
  recipientAddress: '',
  recipientEmail: '',
};

export function IssueCertificatePage() {
  const navigate = useNavigate();
  const { account, isAdmin, isIssuer } = useWeb3();
  const { backendStatus } = useBackend();
  const { markStepComplete, setCurrentCertId } = useDemo();
  const { issueCertificate, isLoading } = useCertificates();

  const [form, setForm] = useState(INITIAL_FORM);
  const [file, setFile] = useState(null);
  const [documentHash, setDocumentHash] = useState('');
  const [isHashing, setIsHashing] = useState(false);
  const [txStep, setTxStep] = useState(null);
  const [txResult, setTxResult] = useState(null);

  const canIssue = isAdmin || isIssuer;

  const handleFormChange = useCallback((field, value) => {
    setForm(prev => ({ ...prev, [field]: value }));
  }, [backendStatus.online]);

  const handleFileSelect = useCallback(async (selectedFile) => {
    if (!isValidFileType(selectedFile)) {
      toast.error('Invalid file type. Please upload PDF, PNG, or JPG');
      return;
    }

    setFile(selectedFile);
    setIsHashing(true);

    try {
      let hash;
      if (backendStatus.online) {
        const result = await hashFileWithBackend(selectedFile);
        hash = result.documentHash;
        toast.success('File hash generated by backend API');
      } else {
        hash = await hashFile(selectedFile);
        toast.success('File hash generated in browser fallback');
      }
      setDocumentHash(hash);
    } catch (error) {
      try {
        const fallbackHash = await hashFile(selectedFile);
        setDocumentHash(fallbackHash);
        toast.success('Backend unavailable. Browser hash fallback used');
      } catch (fallbackError) {
        toast.error('Failed to hash file');
        console.error(error, fallbackError);
      }
    } finally {
      setIsHashing(false);
    }
  }, []);

  const handleFileRemove = useCallback(() => {
    setFile(null);
    setDocumentHash('');
  }, []);

  const generateId = useCallback(() => {
    const newId = generateCertId();
    handleFormChange('certId', newId);
  }, [handleFormChange]);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!form.certId || !form.certName || !form.recipientAddress || !documentHash) {
      toast.error('Please fill in all required fields and upload a file');
      return;
    }

    if (!isValidAddress(form.recipientAddress)) {
      toast.error('Invalid recipient address');
      return;
    }

    setTxStep('preparing');

    try {
      // Generate metadata hash
      const metadata = {
        certId: form.certId,
        certName: form.certName,
        certType: form.certType,
        description: form.description,
        recipientName: form.recipientName,
        recipientEmail: form.recipientEmail,
      };
      const metadataHash = await generateMetadataHash(metadata);

      setTxStep('signing');

      // Calculate expiry timestamp
      const expiresAt = form.expiryDate
        ? Math.floor(new Date(form.expiryDate).getTime() / 1000)
        : 0;

      const result = await issueCertificate({
        certId: form.certId,
        certName: form.certName,
        certType: form.certType,
        documentHash,
        metadataHash,
        recipient: form.recipientAddress,
        expiresAt,
      });

      if (result?.success) {
        setTxResult(result);
        setTxStep('success');
        markStepComplete(3);
        setCurrentCertId(form.certId);
      } else {
        setTxStep(null);
      }
    } catch (error) {
      console.error('Issue error:', error);
      setTxStep(null);
    }
  };

  const resetForm = () => {
    setForm(INITIAL_FORM);
    setFile(null);
    setDocumentHash('');
    setTxStep(null);
    setTxResult(null);
  };

  if (!canIssue) {
    return (
      <Layout>
        <PermissionDenied message="Only Admin or Issuer can issue certificates. For demo, use the deployer wallet or grant issuer role from Issuer Management page." />
      </Layout>
    );
  }

  // Success modal
  if (txStep === 'success' && txResult) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto">
          <div className="glass-card p-8 text-center glow-border">
            <div className="w-16 h-16 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
              <CheckCircle className="w-10 h-10 text-emerald-400" />
            </div>
            <h2 className="text-2xl font-bold text-dark-100 mb-2">Certificate Issued Successfully!</h2>
            <p className="text-dark-400 mb-6">The certificate has been recorded on the blockchain</p>

            <div className="glass-card p-4 text-left mb-6 space-y-4">
              <div className="flex justify-between items-center">
                <span className="text-dark-500">Certificate ID</span>
                <span className="font-mono text-primary-400">{txResult.certId}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-dark-500">Transaction Hash</span>
                <span className="font-mono text-primary-400">{formatAddress(txResult.txHash, 10, 8)}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-dark-500">Block Number</span>
                <span className="text-dark-200">{txResult.blockNumber}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-dark-500">Issuer</span>
                <span className="font-mono text-primary-400">{formatAddress(account)}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-dark-500">Recipient</span>
                <span className="font-mono text-primary-400">{formatAddress(form.recipientAddress)}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-dark-500">Status</span>
                <StatusBadge status="Valid" />
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <button
                onClick={() => navigate(`/certificate/${txResult.certId}`)}
                className="btn-primary"
              >
                <Eye className="w-5 h-5" />
                View Certificate
              </button>
              <button
                onClick={() => navigate(`/verify?id=${txResult.certId}`)}
                className="btn-secondary"
              >
                <QrCode className="w-5 h-5" />
                Generate QR
              </button>
              <button onClick={resetForm} className="btn-ghost">
                <Plus className="w-5 h-5" />
                Issue Another
              </button>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-dark-100">Issue Certificate</h1>
        <p className="text-dark-400">Create a new blockchain-verified certificate</p>
      </div>

      <div className={`glass-card p-4 mb-6 border ${backendStatus.online ? 'border-emerald-500/30' : 'border-amber-500/30'}`}>
        <p className="text-sm text-dark-300">
          Hash engine: {backendStatus.online ? 'Connected to Python backend API' : 'Backend offline, using browser SHA-256 fallback'}
        </p>
      </div>

      {/* Transaction Progress */}
      {txStep && txStep !== 'success' && (
        <div className="glass-card p-6 mb-6 glow-border">
          <div className="flex items-center gap-4">
            <Loader2 className="w-8 h-8 text-primary-400 animate-spin" />
            <div>
              <p className="font-medium text-dark-200">
                {txStep === 'preparing' && 'Preparing transaction...'}
                {txStep === 'signing' && 'Waiting for MetaMask signature...'}
              </p>
              <p className="text-sm text-dark-500">Please confirm the transaction in your wallet</p>
            </div>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="grid lg:grid-cols-3 gap-6">
        {/* Form Sections */}
        <div className="lg:col-span-2 space-y-6">
          {/* Certificate Information */}
          <div className="glass-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <FileText className="w-5 h-5 text-primary-400" />
              <h2 className="font-semibold text-dark-100">Certificate Information</h2>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <label className="label">Certificate ID *</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={form.certId}
                    onChange={(e) => handleFormChange('certId', e.target.value)}
                    placeholder="CERT-XXXXX-XXXX"
                    className="input-field flex-1"
                    required
                  />
                  <button
                    type="button"
                    onClick={generateId}
                    className="btn-secondary px-3"
                    title="Generate ID"
                  >
                    <Plus className="w-5 h-5" />
                  </button>
                </div>
              </div>

              <div>
                <label className="label">Certificate Type *</label>
                <select
                  value={form.certType}
                  onChange={(e) => handleFormChange('certType', e.target.value)}
                  className="select-field"
                >
                  {CERTIFICATE_TYPES.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div className="md:col-span-2">
                <label className="label">Certificate Name *</label>
                <input
                  type="text"
                  value={form.certName}
                  onChange={(e) => handleFormChange('certName', e.target.value)}
                  placeholder="e.g., Blockchain Development Certificate"
                  className="input-field"
                  required
                />
              </div>

              <div className="md:col-span-2">
                <label className="label">Description</label>
                <textarea
                  value={form.description}
                  onChange={(e) => handleFormChange('description', e.target.value)}
                  placeholder="Optional description of the certificate"
                  className="input-field min-h-[80px]"
                  rows={3}
                />
              </div>

              <div>
                <label className="label">Expiry Date</label>
                <input
                  type="date"
                  value={form.expiryDate}
                  onChange={(e) => handleFormChange('expiryDate', e.target.value)}
                  className="input-field"
                  min={new Date().toISOString().split('T')[0]}
                />
              </div>
            </div>
          </div>

          {/* Recipient Information */}
          <div className="glass-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <User className="w-5 h-5 text-primary-400" />
              <h2 className="font-semibold text-dark-100">Recipient Information</h2>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="md:col-span-2">
                <label className="label">Recipient Wallet Address *</label>
                <input
                  type="text"
                  value={form.recipientAddress}
                  onChange={(e) => handleFormChange('recipientAddress', e.target.value)}
                  placeholder="0x..."
                  className="input-field font-mono"
                  required
                />
              </div>

              <div>
                <label className="label">Recipient Name</label>
                <input
                  type="text"
                  value={form.recipientName}
                  onChange={(e) => handleFormChange('recipientName', e.target.value)}
                  placeholder="John Doe"
                  className="input-field"
                />
              </div>

              <div>
                <label className="label">Recipient Email</label>
                <input
                  type="email"
                  value={form.recipientEmail}
                  onChange={(e) => handleFormChange('recipientEmail', e.target.value)}
                  placeholder="john@example.com"
                  className="input-field"
                />
              </div>
            </div>
          </div>

          {/* File Upload */}
          <div className="glass-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <Upload className="w-5 h-5 text-primary-400" />
              <h2 className="font-semibold text-dark-100">Certificate Document *</h2>
            </div>

            <FileUpload
              onFileSelect={handleFileSelect}
              onFileRemove={handleFileRemove}
              file={file}
              documentHash={documentHash}
              isHashing={isHashing}
            />
          </div>
        </div>

        {/* Preview Panel */}
        <div className="lg:col-span-1">
          <div className="glass-card p-6 sticky top-6">
            <div className="flex items-center gap-2 mb-4">
              <Eye className="w-5 h-5 text-primary-400" />
              <h2 className="font-semibold text-dark-100">Preview</h2>
            </div>

            <div className="space-y-4">
              <div>
                <p className="text-xs text-dark-500">Certificate Name</p>
                <p className="text-dark-200">{form.certName || '-'}</p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Certificate ID</p>
                <p className="font-mono text-primary-400">{form.certId || '-'}</p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Type</p>
                <p className="text-dark-200">{form.certType}</p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Recipient</p>
                <p className="text-dark-200">{form.recipientName || '-'}</p>
                {form.recipientAddress && (
                  <p className="font-mono text-xs text-primary-400 mt-1">
                    {formatAddress(form.recipientAddress)}
                  </p>
                )}
              </div>
              <div>
                <p className="text-xs text-dark-500">Issuer</p>
                <p className="font-mono text-xs text-primary-400">{formatAddress(account)}</p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Document Hash</p>
                <p className="font-mono text-xs text-primary-400 break-all">
                  {documentHash ? documentHash.slice(0, 20) + '...' : '-'}
                </p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Status</p>
                <StatusBadge status="Draft" />
              </div>

              <button
                type="submit"
                disabled={isLoading || isHashing || !documentHash}
                className="btn-primary w-full justify-center mt-6"
              >
                {isLoading ? (
                  <>
                    <LoadingSpinner size="sm" />
                    Processing...
                  </>
                ) : (
                  <>
                    <Send className="w-5 h-5" />
                    Issue on Blockchain
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </form>
    </Layout>
  );
}
