import { useState, useCallback, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { useWeb3 } from '../context/Web3Context';
import { useDemo } from '../context/DemoContext';
import { useCertificates } from '../hooks/useCertificates';
import { Layout } from '../components/layout/Layout';
import { FileUpload } from '../components/common/FileUpload';
import { LoadingSpinner, EmptyState } from '../components/common/States';
import { StatusBadge, TypeBadge } from '../components/common/Badges';
import { AddressDisplay, HashDisplay, TimestampDisplay } from '../components/common/Displays';
import { hashFile, isValidFileType } from '../utils/hash';
import { hashFileWithBackend } from '../utils/backendApi';
import { useBackend } from '../context/BackendContext';
import { formatDate, formatAddress } from '../utils/format';
import toast from 'react-hot-toast';
import QRCode from 'react-qr-code';
import {
  Shield,
  Search,
  Upload,
  QrCode,
  CheckCircle,
  XCircle,
  AlertTriangle,
  FileText,
  Download,
  Eye,
  Hash,
  User,
  Building2,
  Calendar,
  Copy,
  ExternalLink,
  Loader2,
  Camera,
} from 'lucide-react';

const TABS = [
  { id: 'id', label: 'Verify by ID', icon: Search },
  { id: 'file', label: 'Verify by File', icon: Upload },
  { id: 'qr', label: 'QR Code', icon: QrCode },
];

export function VerifyCertificatePage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { networkInfo } = useWeb3();
  const { backendStatus } = useBackend();
  const { markStepComplete, currentCertId } = useDemo();
  const { getCertificate, verifyCertificate, certificates } = useCertificates();

  const [activeTab, setActiveTab] = useState('id');
  const [certId, setCertId] = useState(searchParams.get('id') || '');
  const [file, setFile] = useState(null);
  const [documentHash, setDocumentHash] = useState('');
  const [isHashing, setIsHashing] = useState(false);
  const [isVerifying, setIsVerifying] = useState(false);
  const [verificationResult, setVerificationResult] = useState(null);
  const [qrCertId, setQrCertId] = useState('');

  // Auto-verify if ID is in URL
  useEffect(() => {
    const urlId = searchParams.get('id');
    if (urlId && !verificationResult) {
      setCertId(urlId);
      handleVerifyById(urlId);
    }
  }, [searchParams]);

  const handleVerifyById = useCallback(async (id) => {
    const searchId = id || certId;
    if (!searchId.trim()) {
      toast.error('Please enter a certificate ID');
      return;
    }

    setIsVerifying(true);
    setVerificationResult(null);

    try {
      const cert = await getCertificate(searchId);
      if (cert) {
        const verification = await verifyCertificate(searchId);
        setVerificationResult({
          found: true,
          certificate: cert,
          verification,
        });
        markStepComplete(4);
      } else {
        setVerificationResult({ found: false });
      }
    } catch (error) {
      console.error('Verification error:', error);
      setVerificationResult({ found: false, error: error.message });
    } finally {
      setIsVerifying(false);
    }
  }, [certId, getCertificate, verifyCertificate, markStepComplete]);

  const handleFileSelect = useCallback(async (selectedFile) => {
    if (!isValidFileType(selectedFile)) {
      toast.error('Invalid file type. Please upload PDF, PNG, or JPG');
      return;
    }

    setFile(selectedFile);
    setIsHashing(true);
    setVerificationResult(null);

    try {
      let hash;
      if (backendStatus.online) {
        const result = await hashFileWithBackend(selectedFile);
        hash = result.documentHash;
        toast.success('File hash generated by backend API');
      } else {
        hash = await hashFile(selectedFile);
        toast.success('File hash generated in browser fallback');
      }
      setDocumentHash(hash);
    } catch (error) {
      try {
        const fallbackHash = await hashFile(selectedFile);
        setDocumentHash(fallbackHash);
        toast.success('Backend unavailable. Browser hash fallback used');
      } catch (fallbackError) {
        toast.error('Failed to hash file');
        console.error(error, fallbackError);
      }
    } finally {
      setIsHashing(false);
    }
  }, [backendStatus.online]);

  const handleFileRemove = useCallback(() => {
    setFile(null);
    setDocumentHash('');
    setVerificationResult(null);
  }, []);

  const handleVerifyByFile = useCallback(async () => {
    if (!documentHash) {
      toast.error('Please upload a file first');
      return;
    }

    setIsVerifying(true);
    setVerificationResult(null);

    try {
      // Search for certificate with matching document hash
      const matchingCert = certificates.find(c => c.documentHash === documentHash);
      
      if (matchingCert) {
        const verification = await verifyCertificate(matchingCert.certId);
        setVerificationResult({
          found: true,
          certificate: matchingCert,
          verification,
          matchedByFile: true,
        });
        markStepComplete(4);
      } else {
        setVerificationResult({ found: false, matchedByFile: true });
      }
    } catch (error) {
      console.error('Verification error:', error);
      setVerificationResult({ found: false, error: error.message });
    } finally {
      setIsVerifying(false);
    }
  }, [documentHash, certificates, verifyCertificate, markStepComplete]);

  const generateQRValue = (id) => {
    const baseUrl = window.location.origin;
    return `${baseUrl}/verify?id=${id}`;
  };

  const downloadQR = () => {
    const svg = document.getElementById('qr-code');
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();
    img.onload = () => {
      canvas.width = 256;
      canvas.height = 256;
      ctx.fillStyle = 'white';
      ctx.fillRect(0, 0, 256, 256);
      ctx.drawImage(img, 0, 0, 256, 256);
      const pngFile = canvas.toDataURL('image/png');
      const downloadLink = document.createElement('a');
      downloadLink.download = `certificate-${qrCertId}.png`;
      downloadLink.href = pngFile;
      downloadLink.click();
    };
    img.crossOrigin = 'anonymous';
    img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
  };

  const copyToClipboard = (text, label) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard`);
  };

  const renderVerificationResult = () => {
    if (!verificationResult) return null;

    if (!verificationResult.found) {
      return (
        <div className="glass-card p-6 border-l-4 border-l-red-500 mt-6">
          <div className="flex items-center gap-4">
            <XCircle className="w-8 h-8 text-red-400" />
            <div>
              <h3 className="font-semibold text-dark-100">Certificate Not Found</h3>
              <p className="text-dark-400">
                {verificationResult.matchedByFile
                  ? 'No certificate matches this document hash on the blockchain'
                  : 'No certificate found with this ID on the blockchain'
                }
              </p>
            </div>
          </div>
        </div>
      );
    }

    const { certificate, verification } = verificationResult;
    const statusColor = {
      Valid: 'border-l-emerald-500',
      Revoked: 'border-l-red-500',
      Expired: 'border-l-amber-500',
    };
    const statusIcon = {
      Valid: <CheckCircle className="w-8 h-8 text-emerald-400" />,
      Revoked: <XCircle className="w-8 h-8 text-red-400" />,
      Expired: <AlertTriangle className="w-8 h-8 text-amber-400" />,
    };

    return (
      <div className="mt-6 space-y-6">
        {/* Status Banner */}
        <div className={`glass-card p-6 border-l-4 ${statusColor[certificate.statusLabel]}`}>
          <div className="flex items-center gap-4">
            {statusIcon[certificate.statusLabel]}
            <div className="flex-1">
              <h3 className="font-semibold text-dark-100">
                {certificate.statusLabel === 'Valid' && 'Certificate Verified'}
                {certificate.statusLabel === 'Revoked' && 'Certificate Revoked'}
                {certificate.statusLabel === 'Expired' && 'Certificate Expired'}
              </h3>
              <p className="text-dark-400">
                {certificate.statusLabel === 'Valid' && 'This certificate is authentic and currently valid'}
                {certificate.statusLabel === 'Revoked' && `Reason: ${certificate.revokedReason || 'Not specified'}`}
                {certificate.statusLabel === 'Expired' && `Expired on ${formatDate(certificate.expiresAt)}`}
              </p>
            </div>
            <StatusBadge status={certificate.statusLabel} />
          </div>
        </div>

        {/* Certificate Details */}
        <div className="grid md:grid-cols-2 gap-6">
          <div className="glass-card p-6">
            <h3 className="font-semibold text-dark-100 mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary-400" />
              Certificate Information
            </h3>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-dark-500">Certificate Name</p>
                <p className="text-dark-200">{certificate.certName}</p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Certificate ID</p>
                <p className="font-mono text-primary-400">{certificate.certId}</p>
              </div>
              <div>
                <p className="text-xs text-dark-500">Type</p>
                <TypeBadge type={certificate.certType} />
              </div>
              <div>
                <p className="text-xs text-dark-500">Issued At</p>
                <p className="text-dark-200">{formatDate(certificate.issuedAt, true)}</p>
              </div>
              {certificate.expiresAt > 0 && (
                <div>
                  <p className="text-xs text-dark-500">Expires At</p>
                  <p className="text-dark-200">{formatDate(certificate.expiresAt, true)}</p>
                </div>
              )}
            </div>
          </div>

          <div className="glass-card p-6">
            <h3 className="font-semibold text-dark-100 mb-4 flex items-center gap-2">
              <User className="w-5 h-5 text-primary-400" />
              Parties
            </h3>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-dark-500">Issuer</p>
                <AddressDisplay address={certificate.issuer} networkInfo={networkInfo} />
              </div>
              <div>
                <p className="text-xs text-dark-500">Recipient</p>
                <AddressDisplay address={certificate.recipient} networkInfo={networkInfo} />
              </div>
            </div>
          </div>
        </div>

        {/* Hashes */}
        <div className="glass-card p-6">
          <h3 className="font-semibold text-dark-100 mb-4 flex items-center gap-2">
            <Hash className="w-5 h-5 text-primary-400" />
            Cryptographic Verification
          </h3>
          <div className="space-y-3">
            <div>
              <p className="text-xs text-dark-500">Document Hash</p>
              <HashDisplay hash={certificate.documentHash} />
            </div>
            <div>
              <p className="text-xs text-dark-500">Metadata Hash</p>
              <HashDisplay hash={certificate.metadataHash} />
            </div>
            {verificationResult.matchedByFile && (
              <div className="mt-4 p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg">
                <div className="flex items-center gap-2 text-emerald-400">
                  <CheckCircle className="w-5 h-5" />
                  <span>Document hash matches the uploaded file</span>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-3">
          <button
            onClick={() => navigate(`/certificate/${certificate.certId}`)}
            className="btn-primary"
          >
            <Eye className="w-5 h-5" />
            View Full Details
          </button>
          <button
            onClick={() => {
              setQrCertId(certificate.certId);
              setActiveTab('qr');
            }}
            className="btn-secondary"
          >
            <QrCode className="w-5 h-5" />
            Generate QR
          </button>
        </div>
      </div>
    );
  };

  return (
    <Layout>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-dark-100">Verify Certificate</h1>
        <p className="text-dark-400">Verify the authenticity of a certificate on the blockchain</p>
      </div>

      <div className={`glass-card p-4 mb-6 border ${backendStatus.online ? 'border-emerald-500/30' : 'border-amber-500/30'}`}>
        <p className="text-sm text-dark-300">
          File verification engine: {backendStatus.online ? 'Connected to Python backend API' : 'Backend offline, using browser SHA-256 fallback'}
        </p>
      </div>

      {/* Tabs */}
      <div className="glass-card p-1 inline-flex gap-1 mb-6">
        {TABS.map(tab => (
          <button
            key={tab.id}
            onClick={() => {
              setActiveTab(tab.id);
              setVerificationResult(null);
            }}
            className={`px-4 py-2 rounded-lg flex items-center gap-2 transition-colors ${
              activeTab === tab.id
                ? 'bg-primary-500 text-white'
                : 'text-dark-400 hover:text-dark-200 hover:bg-dark-700'
            }`}
          >
            <tab.icon className="w-4 h-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      {activeTab === 'id' && (
        <div className="glass-card p-6">
          <h2 className="font-semibold text-dark-100 mb-4">Enter Certificate ID</h2>
          <div className="flex gap-3">
            <input
              type="text"
              value={certId}
              onChange={(e) => setCertId(e.target.value)}
              placeholder="CERT-XXXXX-XXXX"
              className="input-field flex-1 font-mono"
              onKeyDown={(e) => e.key === 'Enter' && handleVerifyById()}
            />
            <button
              onClick={() => handleVerifyById()}
              disabled={isVerifying}
              className="btn-primary"
            >
              {isVerifying ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Verifying...
                </>
              ) : (
                <>
                  <Shield className="w-5 h-5" />
                  Verify
                </>
              )}
            </button>
          </div>
          {currentCertId && !certId && (
            <button
              onClick={() => setCertId(currentCertId)}
              className="mt-3 text-sm text-primary-400 hover:text-primary-300"
            >
              Use recently issued certificate: {currentCertId}
            </button>
          )}
          {renderVerificationResult()}
        </div>
      )}

      {activeTab === 'file' && (
        <div className="glass-card p-6">
          <h2 className="font-semibold text-dark-100 mb-4">Upload Certificate Document</h2>
          <p className="text-dark-400 mb-4">
            Upload the original certificate document to verify its authenticity by matching the document hash.
          </p>
          <FileUpload
            onFileSelect={handleFileSelect}
            onFileRemove={handleFileRemove}
            file={file}
            documentHash={documentHash}
            isHashing={isHashing}
          />
          {documentHash && (
            <button
              onClick={handleVerifyByFile}
              disabled={isVerifying}
              className="btn-primary mt-4"
            >
              {isVerifying ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Searching...
                </>
              ) : (
                <>
                  <Shield className="w-5 h-5" />
                  Find Certificate
                </>
              )}
            </button>
          )}
          {renderVerificationResult()}
        </div>
      )}

      {activeTab === 'qr' && (
        <div className="grid md:grid-cols-2 gap-6">
          <div className="glass-card p-6">
            <h2 className="font-semibold text-dark-100 mb-4">Generate QR Code</h2>
            <div className="mb-4">
              <label className="label">Certificate ID</label>
              <input
                type="text"
                value={qrCertId}
                onChange={(e) => setQrCertId(e.target.value)}
                placeholder="CERT-XXXXX-XXXX"
                className="input-field font-mono"
              />
            </div>
            {currentCertId && !qrCertId && (
              <button
                onClick={() => setQrCertId(currentCertId)}
                className="text-sm text-primary-400 hover:text-primary-300"
              >
                Use recently issued certificate: {currentCertId}
              </button>
            )}
          </div>

          <div className="glass-card p-6">
            {qrCertId ? (
              <div className="text-center">
                <div className="bg-white p-4 rounded-lg inline-block mb-4">
                  <QRCode
                    id="qr-code"
                    value={generateQRValue(qrCertId)}
                    size={200}
                    level="H"
                  />
                </div>
                <p className="text-sm text-dark-400 mb-4 break-all">
                  {generateQRValue(qrCertId)}
                </p>
                <div className="flex gap-3 justify-center">
                  <button onClick={downloadQR} className="btn-primary">
                    <Download className="w-5 h-5" />
                    Download PNG
                  </button>
                  <button
                    onClick={() => copyToClipboard(generateQRValue(qrCertId), 'Verification URL')}
                    className="btn-secondary"
                  >
                    <Copy className="w-5 h-5" />
                    Copy Link
                  </button>
                </div>
              </div>
            ) : (
              <div className="text-center py-8">
                <QrCode className="w-16 h-16 text-dark-600 mx-auto mb-4" />
                <p className="text-dark-400">Enter a certificate ID to generate QR code</p>
              </div>
            )}
          </div>
        </div>
      )}
    </Layout>
  );
}
