/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CertificateRegistry {
  export type CertificateStruct = {
    merkleRoot: BytesLike;
    certId: string;
    certName: string;
    certType: string;
    documentHash: BytesLike;
    metadataHash: BytesLike;
    issuer: AddressLike;
    recipient: AddressLike;
    issuedAt: BigNumberish;
    expiresAt: BigNumberish;
    status: BigNumberish;
    revokedReason: string;
    ipfsCID: string;
  };

  export type CertificateStructOutput = [
    merkleRoot: string,
    certId: string,
    certName: string,
    certType: string,
    documentHash: string,
    metadataHash: string,
    issuer: string,
    recipient: string,
    issuedAt: bigint,
    expiresAt: bigint,
    status: bigint,
    revokedReason: string,
    ipfsCID: string
  ] & {
    merkleRoot: string;
    certId: string;
    certName: string;
    certType: string;
    documentHash: string;
    metadataHash: string;
    issuer: string;
    recipient: string;
    issuedAt: bigint;
    expiresAt: bigint;
    status: bigint;
    revokedReason: string;
    ipfsCID: string;
  };
}

export interface CertificateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "certificateExists"
      | "getAllCertificateIds"
      | "getCertificate"
      | "getCertificateIPFS"
      | "getCertificatesByIssuer"
      | "getCertificatesByRecipient"
      | "getTotalCertificates"
      | "grantIssuer"
      | "isAdmin"
      | "isCertificateValid"
      | "isIssuer"
      | "issueCertificate"
      | "issuers"
      | "revokeCertificate"
      | "revokeIssuer"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateRevoked"
      | "IssuerGranted"
      | "IssuerRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "certificateExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCertificateIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateIPFS",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificatesByIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificatesByRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCertificates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCertificateValid",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [
      string,
      string,
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certificateExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCertificateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateIPFS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificatesByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificatesByRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCertificateValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    certId: string,
    issuer: AddressLike,
    recipient: AddressLike,
    documentHash: BytesLike,
    merkleRoot: BytesLike
  ];
  export type OutputTuple = [
    certId: string,
    issuer: string,
    recipient: string,
    documentHash: string,
    merkleRoot: string
  ];
  export interface OutputObject {
    certId: string;
    issuer: string;
    recipient: string;
    documentHash: string;
    merkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [
    certId: string,
    revokedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [certId: string, revokedBy: string, reason: string];
  export interface OutputObject {
    certId: string;
    revokedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerGrantedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevokedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertificateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  certificateExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  getAllCertificateIds: TypedContractMethod<[], [string[]], "view">;

  getCertificate: TypedContractMethod<
    [certId: string],
    [CertificateRegistry.CertificateStructOutput],
    "view"
  >;

  getCertificateIPFS: TypedContractMethod<[certId: string], [string], "view">;

  getCertificatesByIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [string[]],
    "view"
  >;

  getCertificatesByRecipient: TypedContractMethod<
    [recipient: AddressLike],
    [string[]],
    "view"
  >;

  getTotalCertificates: TypedContractMethod<[], [bigint], "view">;

  grantIssuer: TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;

  isAdmin: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isCertificateValid: TypedContractMethod<[certId: string], [boolean], "view">;

  isIssuer: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  issueCertificate: TypedContractMethod<
    [
      certId: string,
      certName: string,
      certType: string,
      documentHash: BytesLike,
      metadataHash: BytesLike,
      merkleRoot: BytesLike,
      recipient: AddressLike,
      expiresAt: BigNumberish,
      ipfsCID: string
    ],
    [void],
    "nonpayable"
  >;

  issuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  revokeCertificate: TypedContractMethod<
    [certId: string, reason: string],
    [void],
    "nonpayable"
  >;

  revokeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyCertificate: TypedContractMethod<
    [certId: string, documentHash: BytesLike],
    [
      [boolean, boolean, bigint, string, string, bigint, bigint, string] & {
        exists: boolean;
        hashMatches: boolean;
        status: bigint;
        issuer: string;
        recipient: string;
        issuedAt: bigint;
        expiresAt: bigint;
        merkleRoot: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificateExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllCertificateIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [certId: string],
    [CertificateRegistry.CertificateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificateIPFS"
  ): TypedContractMethod<[certId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getCertificatesByIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCertificatesByRecipient"
  ): TypedContractMethod<[recipient: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalCertificates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCertificateValid"
  ): TypedContractMethod<[certId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isIssuer"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      certId: string,
      certName: string,
      certType: string,
      documentHash: BytesLike,
      metadataHash: BytesLike,
      merkleRoot: BytesLike,
      recipient: AddressLike,
      expiresAt: BigNumberish,
      ipfsCID: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<
    [certId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<
    [certId: string, documentHash: BytesLike],
    [
      [boolean, boolean, bigint, string, string, bigint, bigint, string] & {
        exists: boolean;
        hashMatches: boolean;
        status: bigint;
        issuer: string;
        recipient: string;
        issuedAt: bigint;
        expiresAt: bigint;
        merkleRoot: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerGranted"
  ): TypedContractEvent<
    IssuerGrantedEvent.InputTuple,
    IssuerGrantedEvent.OutputTuple,
    IssuerGrantedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevoked"
  ): TypedContractEvent<
    IssuerRevokedEvent.InputTuple,
    IssuerRevokedEvent.OutputTuple,
    IssuerRevokedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(string,address,address,bytes32,bytes32)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(string,address,string)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "IssuerGranted(address)": TypedContractEvent<
      IssuerGrantedEvent.InputTuple,
      IssuerGrantedEvent.OutputTuple,
      IssuerGrantedEvent.OutputObject
    >;
    IssuerGranted: TypedContractEvent<
      IssuerGrantedEvent.InputTuple,
      IssuerGrantedEvent.OutputTuple,
      IssuerGrantedEvent.OutputObject
    >;

    "IssuerRevoked(address)": TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
    IssuerRevoked: TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
  };
}
