/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DocumentNotaryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchCount"
      | "batchExists"
      | "batches"
      | "getBatch"
      | "notarize"
      | "verifyAndCheck"
      | "verifyDocument"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchNotarized"): EventFragment;

  encodeFunctionData(
    functionFragment: "batchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "batches", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getBatch", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "notarize",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndCheck",
    values: [BytesLike, BytesLike[], boolean[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [BytesLike, BytesLike[], boolean[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "batchCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "notarize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
}

export namespace BatchNotarizedEvent {
  export type InputTuple = [
    merkleRoot: BytesLike,
    submitter: AddressLike,
    fileCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    merkleRoot: string,
    submitter: string,
    fileCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    merkleRoot: string;
    submitter: string;
    fileCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentNotary extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentNotary;
  waitForDeployment(): Promise<this>;

  interface: DocumentNotaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchCount: TypedContractMethod<[], [bigint], "view">;

  batchExists: TypedContractMethod<[root: BytesLike], [boolean], "view">;

  batches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string] & {
        submitter: string;
        timestamp: bigint;
        fileCount: bigint;
        description: string;
      }
    ],
    "view"
  >;

  getBatch: TypedContractMethod<
    [root: BytesLike],
    [
      [string, bigint, bigint, string] & {
        submitter: string;
        timestamp: bigint;
        fileCount: bigint;
        description: string;
      }
    ],
    "view"
  >;

  notarize: TypedContractMethod<
    [merkleRoot: BytesLike, fileCount: BigNumberish, description: string],
    [string],
    "nonpayable"
  >;

  verifyAndCheck: TypedContractMethod<
    [
      leafHash: BytesLike,
      proof: BytesLike[],
      isLeft: boolean[],
      root: BytesLike
    ],
    [[boolean, boolean] & { proofValid: boolean; batchOnChain: boolean }],
    "view"
  >;

  verifyDocument: TypedContractMethod<
    [
      leafHash: BytesLike,
      proof: BytesLike[],
      isLeft: boolean[],
      root: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchExists"
  ): TypedContractMethod<[root: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string] & {
        submitter: string;
        timestamp: bigint;
        fileCount: bigint;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [root: BytesLike],
    [
      [string, bigint, bigint, string] & {
        submitter: string;
        timestamp: bigint;
        fileCount: bigint;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "notarize"
  ): TypedContractMethod<
    [merkleRoot: BytesLike, fileCount: BigNumberish, description: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndCheck"
  ): TypedContractMethod<
    [
      leafHash: BytesLike,
      proof: BytesLike[],
      isLeft: boolean[],
      root: BytesLike
    ],
    [[boolean, boolean] & { proofValid: boolean; batchOnChain: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [
      leafHash: BytesLike,
      proof: BytesLike[],
      isLeft: boolean[],
      root: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BatchNotarized"
  ): TypedContractEvent<
    BatchNotarizedEvent.InputTuple,
    BatchNotarizedEvent.OutputTuple,
    BatchNotarizedEvent.OutputObject
  >;

  filters: {
    "BatchNotarized(bytes32,address,uint256,uint256)": TypedContractEvent<
      BatchNotarizedEvent.InputTuple,
      BatchNotarizedEvent.OutputTuple,
      BatchNotarizedEvent.OutputObject
    >;
    BatchNotarized: TypedContractEvent<
      BatchNotarizedEvent.InputTuple,
      BatchNotarizedEvent.OutputTuple,
      BatchNotarizedEvent.OutputObject
    >;
  };
}
