/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificateRegistry } from "./CertificateRegistry";
export type { DocumentNotary } from "./DocumentNotary";
export * as factories from "./factories";
export { CertificateRegistry__factory } from "./factories/CertificateRegistry__factory";
export { DocumentNotary__factory } from "./factories/DocumentNotary__factory";
